name: Preview build

on:
  push:
    branches:
      - main

env:
  PULL_REQUEST_ID: ${{ github.sha }}

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.S3_KEY_ID }}
          aws-secret-access-key: ${{ secrets.S3_KEY_SECRET }}
          aws-region: eu-central-1

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Rename preview slide
        run: |
          (cd packages/preview-slide && sed 's/preview-slide/preview-slide-${{ github.event.pull_request.number }}/g' package.json > package.json.tmp && mv package.json.tmp package.json)

      - name: Install dependencies
        run: npm install

      - name: Build
        run: |
          cd packages/preview-slide
          npm run build

      - name: Deploy
        run: |
          cd packages/preview-slide
          aws s3 sync ./dist s3://previews-talk-hosting/${{ github.event.pull_request.number }}/preview-slide --acl public-read

      - name: Propagate
        run: |
          curl -X POST ${{ secrets.NOTIFY_URL }} \
            -H "Content-Type: application/json" \
            -d '{"type": "build_complete", "pr_id": "${{ github.event.pull_request.number }}"}'
